name: Metro
version: '1.1.7'
main: org.cubexmc.metro.Metro
api-version: '1.18'
folia-supported: true
authors: [angushushu, wwwer]
description: A simple metro management system / 一个简单的地铁管理系统
website: https://cubexmc.org
softdepend:
  - ViaVersion
  - Geyser-Spigot
  - floodgate
  - Vault
  - BlueMap
  - dynmap
  - squaremap


permissions:
  metro.admin:
    description: Allow use of Metro plugin admin commands
    default: op
    children:
      metro.tp: true
  metro.use:
    description: Allow players to use Metro plugin features (such as riding trains)
    default: true
  metro.gui:
    description: Allow players to open the Metro GUI
    default: true
  metro.tp:
    description: Allow players to teleport to stops via command and GUI
    default: false
  metro.line.create:
    description: Allow players to create new metro lines
    default: false
  metro.stop.create:
    description: Allow players to create new stops
    default: false
  metro.portal.create:
    description: Allow players to create new minecart portals
    default: false
